# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 17:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blurb', models.TextField(max_length=4000)),
                ('score', models.IntegerField()),
                ('sort_order', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('saved', 'Saved'), ('published', 'Published'), ('removed', 'Removed')], max_length=20)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_beginning', models.DateField()),
                ('week_info', models.TextField(max_length=4000)),
                ('current_week', models.BooleanField(help_text='Show as the current scheduled week')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=400)),
                ('mp3_link', models.URLField(blank=True, null=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('web_link', models.URLField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('tagline', models.CharField(max_length=255)),
                ('wordpress_post_id', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('published', 'Published'), ('removed', 'Removed')], max_length=20)),
                ('publish_date', models.DateTimeField(help_text='Schedule a publish time here')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='scheduledweek',
            name='friday',
            field=models.ManyToManyField(related_name='fri_songs', to='blurber.Song'),
        ),
        migrations.AddField(
            model_name='scheduledweek',
            name='monday',
            field=models.ManyToManyField(related_name='mon_songs', to='blurber.Song'),
        ),
        migrations.AddField(
            model_name='scheduledweek',
            name='saturday',
            field=models.ManyToManyField(related_name='sat_songs', to='blurber.Song'),
        ),
        migrations.AddField(
            model_name='scheduledweek',
            name='sunday',
            field=models.ManyToManyField(related_name='sun_songs', to='blurber.Song'),
        ),
        migrations.AddField(
            model_name='scheduledweek',
            name='thursday',
            field=models.ManyToManyField(related_name='thu_songs', to='blurber.Song'),
        ),
        migrations.AddField(
            model_name='scheduledweek',
            name='tuesday',
            field=models.ManyToManyField(related_name='tue_songs', to='blurber.Song'),
        ),
        migrations.AddField(
            model_name='scheduledweek',
            name='wednesday',
            field=models.ManyToManyField(related_name='wed_songs', to='blurber.Song'),
        ),
        migrations.AddField(
            model_name='review',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blurber.Song'),
        ),
        migrations.AddField(
            model_name='review',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
