# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blurber', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-create_date']},
        ),
        migrations.AlterModelOptions(
            name='scheduledweek',
            options={'ordering': ['-week_beginning']},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['-upload_date']},
        ),
        migrations.AddField(
            model_name='song',
            name='display_user_ratings',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='blurb',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(blank=True, choices=[('', 'N/A'), ('draft', 'Draft'), ('saved', 'Saved'), ('published', 'Published'), ('removed', 'Removed')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledweek',
            name='friday',
            field=models.ManyToManyField(blank=True, related_name='fri_songs', to='blurber.Song'),
        ),
        migrations.AlterField(
            model_name='scheduledweek',
            name='monday',
            field=models.ManyToManyField(blank=True, related_name='mon_songs', to='blurber.Song'),
        ),
        migrations.AlterField(
            model_name='scheduledweek',
            name='saturday',
            field=models.ManyToManyField(blank=True, related_name='sat_songs', to='blurber.Song'),
        ),
        migrations.AlterField(
            model_name='scheduledweek',
            name='sunday',
            field=models.ManyToManyField(blank=True, related_name='sun_songs', to='blurber.Song'),
        ),
        migrations.AlterField(
            model_name='scheduledweek',
            name='thursday',
            field=models.ManyToManyField(blank=True, related_name='thu_songs', to='blurber.Song'),
        ),
        migrations.AlterField(
            model_name='scheduledweek',
            name='tuesday',
            field=models.ManyToManyField(blank=True, related_name='tue_songs', to='blurber.Song'),
        ),
        migrations.AlterField(
            model_name='scheduledweek',
            name='wednesday',
            field=models.ManyToManyField(blank=True, related_name='wed_songs', to='blurber.Song'),
        ),
        migrations.AlterField(
            model_name='song',
            name='publish_date',
            field=models.DateTimeField(blank=True, help_text='Schedule a publish time here', null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='tagline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
