# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blurber', '0002_auto_20160216_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='mp3_file',
            field=models.FileField(blank=True, null=True, upload_to='somewhere'),
        ),
    ]
