# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-19 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blurber', '0005_auto_20160310_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='blurb_backup',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
