# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-01 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blurber', '0006_review_blurb_backup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='display_user_ratings',
            field=models.BooleanField(default=True, help_text="I don't know what this does but prob something to do with Wordpress"),
        ),
        migrations.AlterField(
            model_name='song',
            name='image_url',
            field=models.URLField(blank=True, help_text='Will appear on published post.', null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='mp3_file',
            field=models.FileField(blank=True, help_text='Will be available to writers in the blurber only.', null=True, upload_to='somewhere'),
        ),
        migrations.AlterField(
            model_name='song',
            name='mp3_link',
            field=models.URLField(blank=True, help_text='Will be available to writers in the blurber only.', null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='publish_date',
            field=models.DateTimeField(blank=True, help_text='Schedule a publish time here (TODO)', null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('published', 'Published'), ('removed', 'Removed')], default='open', help_text='Close/publish/remove the song here.', max_length=20),
        ),
        migrations.AlterField(
            model_name='song',
            name='tagline',
            field=models.CharField(blank=True, help_text='Will appear on published post.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='web_link',
            field=models.URLField(blank=True, help_text='Will appear on published post', null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='wordpress_post_id',
            field=models.CharField(blank=True, help_text='Auto-filled on publish.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='youtube_link',
            field=models.URLField(blank=True, help_text='Will be available to writers in the blurber AND on published post.', null=True),
        ),
    ]
