# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blurber', '0007_auto_20180401_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='display_user_ratings',
        ),
        migrations.RemoveField(
            model_name='song',
            name='wordpress_post_id',
        ),
    ]
