# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-28 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blurber', '0008_auto_20180402_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='tagline',
            field=models.CharField(blank=True, help_text='Will appear on published post and in search results.', max_length=255, null=True),
        ),
    ]
