# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 17:21
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='writer',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='writer',
            name='username',
            field=models.CharField(default='dummy@address.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='writer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
