# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0004_auto_20160214_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='bio_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
