# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-28 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blurber', '0008_auto_20180402_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_content', models.TextField(help_text='Only edit this in an emergency!')),
                ('visible', models.BooleanField(default=True)),
                ('include_in_search_results', models.BooleanField(default=True)),
                ('published_on', models.DateField()),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blurber.Song')),
            ],
        ),
    ]
