# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-28 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicpost',
            name='published_on',
            field=models.DateTimeField(),
        ),
    ]
