# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-28 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blurber', '0009_auto_20181228_1637'),
        ('tsj', '0004_auto_20181228_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='song',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blurber.Song'),
            preserve_default=False,
        ),
    ]
